### ISSUE TITLE
Only page 1 is downloaded, code hangs for 20 secs on failure

### ISSUE THREAD

**Issue by jordan-bird** [Jebq/Artnet-Scraper#4]
I have added a fix to the bugs here in my pull request: 

https://github.com/Jebq/Artnet-Scraper/pull/3
Fork here: https://github.com/jordan-bird/Artnet-Scraper

This fixes two bugs:
1. Only page 1 is downloaded, now all pages are downloaded
2. An error is checked 20 times with time.sleep(1) between them, meaning a failure to save an image causes the code to hang for 20 seconds. I have changed it so failed images are just skipped rather than waiting for 1-20 seconds to try again

I have also added a progress bar in place of all the links being printed

**Comment by Jebq** [comment]
Fixed in #3
